account-data:
  mail: zursuchetexthiereingeben@existiert.net
  username: t0iletteNm4n567
  name: IchB2inKweinBot
  password: N0bodyNe€dsP4asswords
  birthday: 9.9.1989

proxy-config:
  max_same_proxy: 3
  new_proxy_timeout: 5
  working_proxy_timeout: 7
  working_proxy_retrys: 5
  max_proxy_spam: 3
  max_session_proxy: 10 

log-colors:
  debug: white
  info: green
  warning: red
  error: red
  critical: red

# 1: only successes & errors
# 2: successes & errors and proxy infos
# 3: complete debug output
debug-log-level: 2
