account-data:
  mail: GeborgenLebendigerSteinbock@existiert.net
  username: t0i3452N412
  name: KeinBot
  password: p4s5w0rd
  birthday: 9.9.1989

proxy-config:
  max_same_proxy: 3
  new_proxy_timeout: 5
  working_proxy_timeout: 7
  working_proxy_retrys: 5
  max_proxy_spam: 3
  max_session_proxy: 30

log-colors:
  debug: white
  info: green
  warning: red
  error: red
  critical: red

debug-log-level: 2
backup-logs: 3
