account-data:
  mail: GrenzenlosLebhafterSchimpanse@yeezus.ru
  username: chb1nk3dein14dsf
  name: IchB2inKeinBot
  password: e1n2zig@rt1gesP@5sw0rd
  birthday: 9.9.1989

proxy-config:
  max_same_proxy: 3
  new_proxy_timeout: 5
  working_proxy_timeout: 7
  working_proxy_retrys: 5
  max_proxy_spam: 3
  max_session_proxy: 10 

log-colors:
  debug: white
  info: green
  warning: red
  error: red
  critical: red

# 1: only successes & errors
# 2: successes & errors and proxy infos
# 3: complete debug output
debug-log-level: 2